# Generated by Django 5.1.2 on 2024-11-19 04:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1', models.CharField(default='Discover my Amazing', max_length=100)),
                ('title_part2', models.CharField(default='Art Space!', max_length=100)),
                ('rotating_text', models.TextField(help_text='Enter a JSON array, e.g., ["web interfaces.", "ios and android applications.", "design mockups.", "automation tools."]')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_photo', models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('icq', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('personal_phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CounterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('years_suffix', models.CharField(blank=True, default='+', max_length=10, null=True)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('projects_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('happy_customers', models.PositiveIntegerField(default=0)),
                ('customers_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('honors_awards', models.PositiveIntegerField(default=0)),
                ('honors_suffix', models.CharField(blank=True, default='+', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, unique=True)),
                ('progress', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Hard Skill',
                'verbose_name_plural': 'Hard Skills',
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50, unique=True)),
                ('progress', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Language Skill',
                'verbose_name_plural': 'Language Skills',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thum_designation_1', models.CharField(max_length=100)),
                ('thum_designation_2', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='personal_info/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('kaggle', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('stack_overflow', models.URLField(blank=True, null=True)),
                ('quora', models.URLField(blank=True, null=True)),
                ('hackerrank', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('features', models.JSONField()),
                ('popular', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('star_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.category')),
            ],
        ),
    ]
