# Generated by Django 5.1.2 on 2024-11-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_knowledgeitem_options_knowledgeitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='personal_info/cv/'),
        ),
    ]
